# -*- coding: utf-8 -*-
"""Amazon Prime data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBh7ZNxp45Q_YU0S6iJM2eJzi0qCVmJQ
"""



# Install missing libraries
!pip install pandas numpy scikit-learn matplotlib seaborn

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
df = pd.read_csv('amazon_prime_titles.csv')

# Display first few rows
df.head()

# Drop duplicates
df.drop_duplicates(inplace=True)

# Handle missing values (fill or drop)
df.fillna("Unknown", inplace=True)

# Convert 'date_added' to datetime
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Convert categorical columns to lowercase for consistency
df['type'] = df['type'].str.lower()
df['rating'] = df['rating'].str.lower()

# Check updated data
df.info()

# Count of movie vs TV show
sns.countplot(x='type', data=df, palette='coolwarm')
plt.title("Distribution of Movies and TV Shows")
plt.show()

# Top 10 countries with most content
df['country'].value_counts().head(10).plot(kind='bar', color='teal')
plt.title("Top 10 Countries Producing Content")
plt.xlabel("Country")
plt.ylabel("Count")
plt.show()

# Encode categorical columns
label_enc = LabelEncoder()
df['type'] = label_enc.fit_transform(df['type'])  # Movie = 1, TV Show = 0
df['rating'] = label_enc.fit_transform(df['rating'])

# Create new feature: Content Age (Years since release)
df['content_age'] = 2024 - df['release_year']

# Check updated dataset
df[['type', 'rating', 'content_age']].head()

# Select features and target
X = df[['release_year', 'rating', 'content_age']]
y = df['type']

# Split into train-test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Convert descriptions to lowercase
df['description'] = df['description'].fillna("").str.lower()

# Apply TF-IDF Vectorization
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['description'])

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Function to recommend movies
def recommend(title):
    index = df[df['title'].str.lower() == title.lower()].index
    if len(index) == 0:
        return "Title not found!"
    index = index[0]

    # Get similarity scores
    sim_scores = list(enumerate(cosine_sim[index]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:6]  # Top 5 similar
    movie_indices = [i[0] for i in sim_scores]

    return df.iloc[movie_indices][['title', 'type', 'description']]

# Example: Recommend movies similar to "Inception"
recommend("The Secret Life of Us")